apiVersion: batch/v1
kind: CronJob
metadata:
  name: elt-copy-workout
  namespace: bigintensive
  labels:
    app: elt-copy-workout
    tier: data
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        metadata:
          labels:
            app: elt-copy-workout
            tier: data
        spec:
          restartPolicy: OnFailure
          containers:
            - name: elt-copy-workout
              image: davidefast/elt-mirror-postgresql-to-clickhouse:latest
              imagePullPolicy: Always
              env:
                - name: POSTGRES_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: bigintensive-config
                      key: POSTGRES_HOST
                - name: POSTGRES_PORT
                  valueFrom:
                    configMapKeyRef:
                      name: bigintensive-config
                      key: POSTGRES_PORT
                - name: POSTGRES_DB
                  valueFrom:
                    configMapKeyRef:
                      name: bigintensive-config
                      key: POSTGRES_DB
                - name: POSTGRES_USER
                  valueFrom:
                    secretKeyRef:
                      name: bigintensive-secrets
                      key: POSTGRES_USER
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: bigintensive-secrets
                      key: POSTGRES_PASSWORD
                - name: CLICKHOUSE_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: bigintensive-config
                      key: CLICKHOUSE_HOST
                - name: CLICKHOUSE_PORT
                  valueFrom:
                    configMapKeyRef:
                      name: bigintensive-config
                      key: CLICKHOUSE_PORT
                - name: CLICKHOUSE_DB
                  valueFrom:
                    configMapKeyRef:
                      name: bigintensive-config
                      key: CLICKHOUSE_DB
                - name: CLICKHOUSE_USER
                  valueFrom:
                    configMapKeyRef:
                      name: bigintensive-config
                      key: CLICKHOUSE_USER
                - name: CLICKHOUSE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: bigintensive-secrets
                      key: CLICKHOUSE_PASSWORD
              resources:
                requests:
                  cpu: "100m"
                  memory: "128Mi"
                limits:
                  cpu: "500m"
                  memory: "512Mi"
